## Test for Complexity Index, turbulence, and entropy

In [1]:
from sequenzo import *
import pandas as pd

In [2]:
# ===============================
#             CO2
# ===============================
df = pd.read_csv("/Users/xinyi/Projects/sequenzo/sequenzo/data_and_output/orignal data/country_co2_emissions_missing.csv")
# df = load_dataset("country_co2_emissions")
_time = list(df.columns)[1:]
states = ['Very Low', 'Low', 'Middle', 'High', 'Very High']
sequence_data = SequenceData(df, time=_time, id_col="country", states=states)

# get_complexity_index(sequence_data)

# get_cross_sectional_entropy(sequence_data)

# get_state_freq_and_entropy_per_seq(sequence_data)

# get_spell_duration_variance(sequence_data)

# get_within_sequence_entropy(sequence_data)

# get_turbulence(sequence_data)

# plot_longitudinal_characteristics(sequence_data)

refseq = [[0, 1, 2], [3, 4, 5]]

get_distance_matrix(sequence_data, method="LCP", sm="TRATE", indel="auto")

[!] Detected missing values (empty cells) in the sequence data.
    â†’ Automatically added 'Missing' to `states` and `labels` for compatibility.
    However, it's strongly recommended to manually include it when defining `states` and `labels`.
    For example:

        states = ['At Home', 'Left Home', 'Missing']
        labels = ['At Home', 'Left Home', 'Missing']

    This ensures consistent color mapping and avoids unexpected visualization errors.

[>] SequenceData initialized successfully! Here's a summary:
[>] Number of sequences: 194
[>] Number of time points: 223
[>] Min/Max sequence length: 216 / 223
[>] There are 7 missing values across 1 sequences.
    First few missing sequence IDs: ['Panama'] ...
[>] Top sequences with the most missing time points:
    (Each row shows a sequence ID and its number of missing values)

             Missing Count
Sequence ID
Panama                   7
[>] States: ['Very Low', 'Low', 'Middle', 'High', 'Very High', 'Missing']
[>] Labels: ['Very Low', 'Low', 'Middle', 'High', 'Very High', 'Missing']
[>] Weights: Not provided
[>] Processing 194 sequences with 6 unique states.
[>] Identified 192 unique sequences.
[>] Starting (Reverse) Longest Common Prefix(LCP/RLCP)...
[>] Computing all pairwise distances...
[>] Computed Successfully.

,Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,...,Uganda,Ukraine,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
Afghanistan,0.0,176.0,192.0,446.0,446.0,446.0,446.0,314.0,446.0,446.0,...,242.0,326.0,358.0,326.0,446.0,218.0,446.0,166.0,446.0,446.0
Albania,176.0,0.0,192.0,446.0,446.0,446.0,446.0,314.0,446.0,446.0,...,242.0,326.0,358.0,326.0,446.0,218.0,446.0,176.0,446.0,446.0
Algeria,192.0,192.0,0.0,446.0,446.0,446.0,446.0,314.0,446.0,446.0,...,242.0,326.0,358.0,326.0,446.0,218.0,446.0,192.0,446.0,446.0
Andorra,446.0,446.0,446.0,0.0,446.0,446.0,446.0,446.0,446.0,446.0,...,446.0,446.0,446.0,446.0,446.0,446.0,446.0,446.0,250.0,446.0
Angola,446.0,446.0,446.0,446.0,0.0,332.0,446.0,446.0,446.0,446.0,...,446.0,446.0,446.0,446.0,330.0,446.0,260.0,446.0,446.0,446.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,218.0,218.0,218.0,446.0,446.0,446.0,446.0,314.0,446.0,446.0,...,242.0,326.0,358.0,326.0,446.0,0.0,446.0,218.0,446.0,446.0
Vietnam,446.0,446.0,446.0,446.0,260.0,332.0,446.0,446.0,446.0,446.0,...,446.0,446.0,446.0,446.0,330.0,446.0,0.0,446.0,446.0,446.0
Yemen,166.0,176.0,192.0,446.0,446.0,446.0,446.0,314.0,446.0,446.0,...,242.0,326.0,358.0,326.0,446.0,218.0,446.0,0.0,446.0,446.0
Zambia,446.0,446.0,446.0,250.0,446.0,446.0,446.0,446.0,446.0,446.0,...,446.0,446.0,446.0,446.0,446.0,446.0,446.0,446.0,0.0,446.0
Zimbabwe,446.0,446.0,446.0,446.0,446.0,446.0,346.0,446.0,324.0,368.0,...,446.0,446.0,446.0,446.0,446.0,446.0,446.0,446.0,446.0,0.0

In [2]:
# ===============================
#            detailed
# ===============================
df = pd.read_csv("/Users/xinyi/Projects/sequenzo/sequenzo/data_and_output/sampled_data_sets/detailed_data/sampled_1000_data.csv")
_time = list(df.columns)[4:]
states = ['data', 'data & intensive math', 'hardware', 'research', 'software', 'software & hardware', 'support & test']
sequence_data = SequenceData(df[['worker_id', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10']],
                             time=_time, id_col="worker_id", states=states)

# get_distance_matrix(sequence_data, method="OMspell", sm="CONSTANT", indel="auto")

clara(sequence_data,
       R=2,
       sample_size=500,
       kvals=range(2, 6),
       criteria=['distance'],
       dist_args={"method": "OMspell", "sm": "INDELS", "indel": 1},
       parallel=True,
       stability=True)

[>] SequenceData initialized successfully! Here's a summary:
[>] Number of sequences: 1000
[>] Number of time points: 10
[>] Min/Max sequence length: 10 / 10
[>] States: ['data', 'data & intensive math', 'hardware', 'research', 'software', 'software & hardware', 'support & test']
[>] Labels: ['data', 'data & intensive math', 'hardware', 'research', 'software', 'software & hardware', 'support & test']
[>] Weights: Not provided
[>] Starting generalized CLARA for sequence analysis.
[>] Using crisp clustering optimizing the following criterion: distance.
  - Aggregating 1000 sequences...
  - OK (184 unique cases).
[>] Starting iterations...

[>] Starting Partitioning Around Medoids with a Once-Only Swap Pass (PAMonce)...
[>] Computed successfully.
[>] Starting Partitioning Around Medoids with a Once-Only Swap Pass (PAMonce)...
[>] Computed successfully.
[>] Starting Partitioning Around Medoids with a Once-Only Swap Pass (PAMonce)...
[>] Computed successfully.
[>] Starting Partitioning Around Medoids with a Once-Only Swap Pass (PAMonce)...
[>] Computed successfully.
[>] Starting Partitioning Around Medoids with a Once-Only Swap Pass (PAMonce)...
[>] Computed successfully.
[>] Starting Partitioning Around Medoids with a Once-Only Swap Pass (PAMonce)...
[>] Computed successfully.
[>] Starting Partitioning Around Medoids with a Once-Only Swap Pass (PAMonce)...
[>] Computed successfully.
[>] Starting Partitioning Around Medoids with a Once-Only Swap Pass (PAMonce)...
[>] Computed successfully.

IndexError: index 1081520128 is out of bounds for axis 0 with size 86

In [4]:
# ===============================
#             broad
# ===============================
df = pd.read_csv("/Users/xinyi/Projects/sequenzo/sequenzo/data_and_output/sampled_data_sets/broad_data/sampled_1000_data.csv")
_time = list(df.columns)[4:]
states = ['Non-computing', 'Non-technical computing', 'Technical computing']
sequence_data = SequenceData(df[['worker_id', 'C1', 'C2', 'C3', 'C4', 'C5']],
                             time=_time, id_col="worker_id", states=states)
res = get_complexity_index(sequence_data)

res

[>] SequenceData initialized successfully! Here's a summary:
[>] Number of sequences: 1000
[>] Number of time points: 5
[>] Min/Max sequence length: 5 / 5
[>] States: ['Non-computing', 'Non-technical computing', 'Technical computing']
[>] Labels: ['Non-computing', 'Non-technical computing', 'Technical computing']
[>] Weights: Not provided

                                ComplexityIndex
tom-williams-9b982013b                 0.000000
emily-jacobs-b62a95237                 0.000000
alok-maheshwari-5879243                0.000000
harikarani                             0.000000
rasoolbabushaik                        0.000000
...                                         ...
tejaswini-chinta-23714659              0.000000
komal93                                0.000000
sanjay-sudheer-9a3718163               0.000000
jeff-stieglitz-3a2a086                 0.000000
syed-tajamul-hussain-35469713a         0.337448

[1000 rows x 1 columns]

In [5]:
# ===============================
#             Sohee
# ===============================
df = pd.read_csv('/Users/xinyi/Projects/sequenzo/sequenzo/data_and_output/orignal data/sohee/sequence_data.csv')
time_list = list(df.columns)[1:133]
states = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]
# states = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
labels = ['FT+WC', 'FT+BC', 'PT+WC', 'PT+BC', 'U', 'OLF']
sequence_data = SequenceData(df, time=time_list, states=states, labels=labels, id_col="PID")

get_distance_matrix(sequence_data, method="OMspell", sm="TRATE", indel="auto")

[!] Detected missing values (empty cells) in the sequence data.
    â†’ Automatically added np.nan to `states` and `labels` for compatibility.
    However, it's strongly recommended to manually include it when defining `states` and `labels`.
    For example:

        states = [At Home, Left Home, np.nan]
        labels = [At Home, Left Home, Missing]

    This ensures consistent color mapping and avoids unexpected visualization errors.

[>] SequenceData initialized successfully! Here's a summary:
[>] Number of sequences: 6576
[>] Number of time points: 132
[>] Min/Max sequence length: 15 / 132
[>] There are 24692 missing values across 2050 sequences.
    First few missing sequence IDs: [11, 18, 27, 33, 49, 54, 57, 58, 63, 68] ...
[>] Top sequences with the most missing time points:
    (Each row shows a sequence ID and its number of missing values)

             Missing Count
Sequence ID
4415                   117
7574                    81
8232                    68
4970                    65
3449                    60
[>] States: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, nan]
[>] Labels: ['FT+WC', 'FT+BC', 'PT+WC', 'PT+BC', 'U', 'OLF', 'Missing']
[>] Weights: Not provided
[>] Processing 6576 sequences with 7 unique states.
[>] Transition-based substitution-cost matrix (TRATE) initiated...
  - Computing transition probabilities for: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, nan]
[>] generated an indel of type number

[>] Identified 5521 unique spell sequences.
[>] Starting Optimal Matching with spell(OMspell)...
[>] Computing all pairwise distances...
[>] Computed Successfully.

,2,3,4,6,8,10,11,13,16,17,...,12300,12303,12304,12305,12514,12515,12516,12517,12558,12643
2,0.000000,117.500000,69.947125,13.500000,65.500000,125.437228,63.000000,60.500000,87.948903,27.448903,...,134.966333,134.466333,127.393610,84.500000,126.893610,128.393610,127.393610,128.466333,124.446805,84.948903
3,117.500000,0.000000,92.356715,124.000000,94.947125,108.758129,115.500000,112.000000,106.396028,114.947125,...,141.417279,140.917279,74.955861,91.000000,62.500000,108.000000,105.790419,123.917279,55.893610,108.289958
4,69.947125,92.356715,0.000000,72.500000,37.500000,127.352699,73.947125,49.500000,65.947125,63.447125,...,139.917279,139.417279,114.335974,62.328865,115.893610,121.295198,123.364084,132.383612,109.342513,56.793834
6,13.500000,124.000000,72.500000,0.000000,64.000000,136.968614,63.500000,59.000000,90.500000,28.000000,...,133.500000,133.000000,138.946805,90.000000,138.446805,139.946805,138.946805,134.946805,136.000000,85.500000
8,65.500000,94.947125,37.500000,64.000000,0.000000,133.852699,69.500000,39.000000,71.500000,65.000000,...,139.417279,138.917279,119.842513,55.000000,124.395708,124.742608,131.866182,134.917279,116.000000,57.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12515,128.393610,108.000000,121.295198,139.946805,124.742608,80.000000,141.393610,137.893610,140.291416,140.842513,...,125.500000,125.000000,76.922193,129.862223,80.417279,0.000000,80.882061,94.000000,104.681400,141.291416
12516,127.393610,105.790419,123.364084,138.946805,131.866182,65.967710,121.415419,137.915419,139.291416,139.842513,...,81.500000,94.000000,102.856106,131.893610,94.290419,80.882061,0.000000,80.882061,106.756752,128.242417
12517,128.466333,123.917279,132.383612,134.946805,134.917279,84.882061,136.415419,132.968614,135.446805,135.895708,...,47.500000,47.000000,112.834558,126.883612,113.334558,94.000000,80.882061,0.000000,127.883612,136.500000
12558,124.446805,55.893610,109.342513,136.000000,116.000000,110.755200,133.500000,130.000000,126.446805,132.946805,...,143.417279,142.917279,76.955861,119.840414,54.382061,104.681400,106.756752,127.883612,0.000000,127.291416
12643,84.948903,108.289958,56.793834,85.500000,57.500000,141.212891,66.000000,67.446805,62.000000,67.500000,...,124.917279,137.417279,140.082831,66.303840,139.582831,141.291416,128.242417,136.500000,127.291416,0.000000

In [ ]:
# ===============================
#            kass
# ===============================
df = pd.read_csv('/Users/xinyi/Projects/sequenzo/sequenzo/data_and_output/orignal data/sohee/wide_civil_final_df.csv')
time_list = list(df.columns)[1:]
states = ['Extensive Warfare', 'Limited Violence', 'No Violence', 'Pervasive Warfare', 'Prolonged Warfare',
          'Serious Violence', 'Serious Warfare', 'Sporadic Violence', 'Technological Warfare', 'Total Warfare']
sequence_data = SequenceData(df, time=time_list, states=states, id_col="COUNTRY")
res = get_complexity_index(sequence_data)

res

In [3]:
# ===============================
#            U
# ===============================
df = pd.read_csv("/Users/xinyi/Projects/sequenzo/sequenzo/data_and_output/orignal data/not_real_detailed_data/synthetic_detailed_U50_N30000.csv")

sequence_data = SequenceData(
    df,
    time=list(df.columns)[1:],
    states=["Data", "Data science", "Hardware", "Research",
            "Software", "Support & test", "Systems & infrastructure"],
    id_col="id"
)

get_distance_matrix(sequence_data, method="OMspell", sm="TRATE", indel="auto")

[>] SequenceData initialized successfully! Here's a summary:
[>] Number of sequences: 30000
[>] Number of time points: 11
[>] Min/Max sequence length: 11 / 11
[>] States: ['Data', 'Data science', 'Hardware', 'Research', 'Software', 'Support & test', 'Systems & infrastructure']
[>] Labels: ['Data', 'Data science', 'Hardware', 'Research', 'Software', 'Support & test', 'Systems & infrastructure']
[>] Weights: Not provided
[>] Processing 30000 sequences with 7 unique states.
[>] Transition-based substitution-cost matrix (TRATE) initiated...
  - Computing transition probabilities for: [Data, Data science, Hardware, Research, Software, Support & test, Systems & infrastructure]
[>] generated an indel of type number

[>] Identified 19537 unique spell sequences.
[>] Starting Optimal Matching with spell(OMspell)...
[>] Computing all pairwise distances...
[>] Computed Successfully.

,33554,9428,200,12448,39490,42725,10823,49499,4145,36959,...,6062,11400,21345,49405,11424,31667,45945,18535,49863,35688
33554,0.000000,6.940005,8.870373,8.756189,13.547416,11.576320,11.586452,10.173724,6.880009,12.087359,...,10.126927,11.587292,10.820014,9.848465,8.756189,11.566684,10.329402,7.350011,13.094723,12.922502
9428,6.940005,0.000000,9.810377,8.730416,10.628021,8.636316,8.743637,8.271175,7.859400,9.147355,...,8.193009,11.596929,10.773678,9.815283,6.756189,10.688674,9.303630,8.410007,10.158018,10.226191
200,8.870373,9.810377,0.000000,9.704397,11.623237,12.490598,4.656924,9.986163,10.820014,10.211180,...,7.248847,10.538984,9.617325,8.574106,8.675270,10.550594,10.198889,12.098937,10.095563,10.988095
12448,8.756189,8.730416,9.704397,0.000000,10.820014,11.672468,10.704397,10.350011,7.940005,9.245403,...,11.949415,8.880009,7.675270,11.603233,8.588781,6.805021,9.205268,8.410007,10.350011,8.275023
39490,13.547416,10.628021,11.623237,10.820014,0.000000,9.645938,10.703609,12.084759,12.683788,10.222162,...,11.094775,9.741177,10.697302,10.567102,11.688356,10.743637,10.290016,11.233554,4.470002,9.233607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31667,11.566684,10.688674,10.550594,6.805021,10.743637,7.880009,7.880009,9.226191,9.848465,8.152765,...,9.350011,9.880009,6.820014,8.880009,8.481313,0.000000,9.275023,11.205268,10.350011,5.410007
45945,10.329402,9.303630,10.198889,9.205268,10.290016,10.101154,11.033749,6.764393,10.205268,12.465682,...,11.510899,9.126927,8.292066,10.248989,9.350011,9.275023,0.000000,9.735266,9.820014,11.473109
18535,7.350011,8.410007,12.098937,8.410007,11.233554,9.378463,11.350011,11.596434,4.470002,9.880009,...,11.696193,11.350011,12.119500,11.152765,10.188060,11.205268,9.735266,0.000000,10.764393,10.724645
49863,13.094723,10.158018,10.095563,10.350011,4.470002,10.175936,9.196187,11.664800,12.213786,10.759569,...,9.704397,7.271175,10.303676,9.234395,11.236503,10.350011,9.820014,10.764393,0.000000,9.822064
35688,12.922502,10.226191,10.988095,8.275023,9.233607,5.286186,7.410007,11.617357,12.126927,7.880009,...,8.859400,9.410007,9.290016,9.226191,8.106318,5.410007,11.473109,10.724645,9.822064,0.000000

## parifam_family

In [1]:
# Import necessary libraries
# Your calling code (e.g., in a script or notebook)

from sequenzo import * # Import the package, give it a short alias
import pandas as pd # Data manipulation

df = load_dataset('pairfam_family')

# Show the dataframe
df

,id,weight40,sex,doby_gen,dob,ethni,migstatus,yeduc,sat1i4,sat5,...,255,256,257,258,259,260,261,262,263,264
0,111000.0,0.343964,1,1971,855,1,1,11.5,5,7,...,4,4,4,4,4,4,4,4,4,4
1,1624000.0,1.467063,1,1973,880,1,1,11.5,9,8,...,8,8,8,8,8,8,8,8,8,8
2,2767000.0,0.463918,1,1971,853,1,1,9.0,9,-2,...,8,8,8,8,8,8,8,8,8,8
3,2931000.0,1.767455,0,1973,881,5,3,10.5,5,5,...,9,9,9,9,9,9,9,9,9,9
4,3167000.0,0.884521,1,1973,883,1,1,11.5,8,10,...,8,8,8,8,8,8,8,8,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1861,919347000.0,0.964979,0,1973,880,1,1,11.5,8,4,...,1,1,1,1,1,1,1,1,1,1
1862,919488000.0,1.981277,0,1971,863,1,1,10.5,10,2,...,9,9,9,9,9,9,9,9,9,9
1863,919910000.0,0.485150,1,1973,878,1,1,20.0,7,7,...,8,8,8,8,8,8,8,8,8,8
1864,920140000.0,2.022823,0,1971,859,1,1,11.5,10,10,...,7,7,7,7,7,7,7,7,7,7
1865,920303000.0,0.620611,1,1971,860,1,1,14.0,10,6,...,6,6,6,6,6,6,6,6,6,6

In [2]:
# 1) Define time and states (order matters!)
time_list = [f"{i}" for i in range(1, 265)]  # 264 months
states = list(range(1, 10))                  # 1..9

# 2) Human-readable labels (strings)
labels = [
    "Single, no child",
    "LAT, no child",
    "Cohabiting, no child",
    "Married, no child",
    "Single, with child(ren)",
    "LAT, with child(ren)",
    "Cohabiting, with child(ren)",
    "Married, 1 child",
    "Married, 2+ children"
]

# 3) A fresh palette (9 colors, same order as 'states')
colors_list = [
    "#74C9B4",  # fresh green
    "#A6E3D0",  # water mint
    "#F9E79F",  # pale apricot
    "#F6CDA3",  # warm light orange
    "#F5B7B1",  # soft rose
    "#D7BDE2",  # light lavender
    "#A3C4F3",  # porcelain blue
    "#7FB3D5",  # lake blue
    "#EAECEE"   # cloud white
]

sequence_data = SequenceData(
    df,
    time=time_list,
    id_col="id",
    states=states,
    labels=labels,
    # If your data do not contain weight, then no need to include the following parameter
    weights=df["weight40"].values,
    custom_colors=colors_list
)

[>] SequenceData initialized successfully! Here's a summary:
[>] Number of sequences: 1866
[>] Number of time points: 264
[>] Min/Max sequence length: 264 / 264
[>] States: [1, 2, 3, 4, 5, 6, 7, 8, 9]
[>] Labels: ['Single, no child', 'LAT, no child', 'Cohabiting, no child', 'Married, no child', 'Single, with child(ren)', 'LAT, with child(ren)', 'Cohabiting, with child(ren)', 'Married, 1 child', 'Married, 2+ children']
[>] Weights: Provided (total weight=2346.268, mean=1.257, std=1.046)

In [3]:
om = get_distance_matrix(seqdata=sequence_data,
                         method="OM",
                         sm="CONSTANT",
                         indel=1)
om

[>] Processing 1866 sequences with 9 unique states.
  - Creating 10x10 substitution-cost matrix using 2 as constant value
[>] Identified 1857 unique sequences.
[>] Starting Optimal Matching(OM)...
[>] Computing all pairwise distances...
[>] Computed Successfully.

,111000.0,1624000.0,2767000.0,2931000.0,3167000.0,3450000.0,3491000.0,3902000.0,4814000.0,5678000.0,...,918511000.0,918595000.0,918958000.0,919111000.0,919206000.0,919347000.0,919488000.0,919910000.0,920140000.0,920303000.0
111000.0,0.0,498.0,498.0,498.0,498.0,266.0,416.0,498.0,518.0,508.0,...,498.0,508.0,528.0,406.0,528.0,528.0,500.0,518.0,508.0,502.0
1624000.0,498.0,0.0,274.0,210.0,226.0,386.0,302.0,314.0,374.0,366.0,...,106.0,368.0,346.0,398.0,378.0,378.0,400.0,232.0,268.0,274.0
2767000.0,498.0,274.0,0.0,382.0,214.0,480.0,444.0,440.0,436.0,372.0,...,274.0,470.0,502.0,466.0,502.0,502.0,502.0,404.0,334.0,380.0
2931000.0,498.0,210.0,382.0,0.0,340.0,346.0,314.0,218.0,268.0,270.0,...,154.0,380.0,274.0,358.0,282.0,282.0,350.0,166.0,326.0,270.0
3167000.0,498.0,226.0,214.0,340.0,0.0,384.0,400.0,394.0,370.0,350.0,...,186.0,428.0,458.0,480.0,458.0,508.0,506.0,344.0,222.0,324.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919347000.0,528.0,378.0,502.0,282.0,508.0,508.0,374.0,378.0,476.0,184.0,...,402.0,414.0,120.0,390.0,78.0,0.0,408.0,256.0,408.0,268.0
919488000.0,500.0,400.0,502.0,350.0,506.0,390.0,380.0,352.0,424.0,404.0,...,350.0,434.0,400.0,148.0,422.0,408.0,0.0,400.0,406.0,336.0
919910000.0,518.0,232.0,404.0,166.0,344.0,420.0,272.0,260.0,314.0,262.0,...,228.0,344.0,204.0,386.0,260.0,256.0,400.0,0.0,296.0,220.0
920140000.0,508.0,268.0,334.0,326.0,222.0,454.0,238.0,308.0,372.0,272.0,...,272.0,352.0,344.0,378.0,392.0,408.0,406.0,296.0,0.0,268.0
920303000.0,502.0,274.0,380.0,270.0,324.0,444.0,260.0,350.0,440.0,268.0,...,254.0,434.0,212.0,334.0,268.0,268.0,336.0,220.0,268.0,0.0